[project]
name = "mlflow-federation-client"
version = "1.0.0"
description = "Flower + MLflow Client App"
dependencies = [
    "mlflow",
    "optuna",
    "scikit-learn",
    "xgboost",
    "pandas",
    "numpy",
    "matplotlib",
    "tensorflow",
    "protobuf"
]

[tool.flwr.app]
publisher = "acs"
