imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
replicaCount: 1

#Shared values are anchored, it is advised to only change these values
#And NOT OVERRIDE where they are referenced
shared_values:
  #Admin minio account, used by mlflow tracking server
  minio_root_user: &MINIO_ROOT_USER "minio_user"
  minio_root_password: &MINIO_ROOT_PASSWORD "minio_pwd"
  minio_default_bucket: &MINIO_DEFAULT_BUCKET "mlflow"
  minio_port: &MINIO_PORT 9000
  #Admin postgres account, used by mlflow tracking server
  postgres_user: &POSTGRES_USER "mlflow"
  postgres_password: &POSTGRES_PASSWORD "mlflow"
  postgres_db: &POSTGRES_DATABASE "mlflow"
  postgres_port: &POSTGRES_PORT 5432
  hub_admin_token: &HUB_ADMIN_TOKEN "cGFzcwo=" #"<put some base64 encoded string here>"

#Jupyterhub is configured to use an auth_state_hook
#In order to create an mlflow account for any user
#Redirected from the specified keycloak (external or managed by this chart)
#It also takes into account group permissions
#Each standard user gets their own mlflow workspace
#Admins have access to all workspaces in the mlflow tracking server
auth:
  #These values have different meanings, depending on whether keycloak is external
  #If keycloak is managed by this chart, then these values will be used to generate
  #The client for this app. If keycloak is external, then it is assumed that the client
  #For this app is configured with these values
  client_id: "jhub-mlfw"
  client_secret: ""
  #Keycloak bootstrapping credentials for generating a master realm + admin user
  kc_admin: "admin"
  kc_admin_pass: "admin"
  #In some cluster setups, the certs may NOT be selfsigned, but still not recognized
  #By the hub anyway, this field deactivates tls verification between the hub and Keycloak
  #Temporary, Until further considerations can be made to instruct the hub to recognize
  #Certain certs, maybe passed by CM name and namespace
  insecure_skip_verify: true
  external:
    enabled: false
    realm_url: "https://tef-dso-keycloak.k8s.eonerc.rwth-aachen.de/realms/tef-dso"
    #The groups claim, changing this may require re-configuring the keycloak
    #Client scope to account for the nesting of claims
    groups_key: "oauth_user.roles"
    #Standard user groups
    allowed_groups:
      - mlfw-user
    #Admin user groups
    admin_groups:
      - mlfw-admin

#Exposing may be achieved using one of two kubernetes API's
#Ingress or Gateways. This is due to the current transition to the Gateways API
#In all implementations that used to support ingress
expose:
  enabled: true
  gateway:
    #A gateway with a proper https listener is assumed to exist
    #Any exposition will fail silently if it doesnt in the case where type=gateway
    default_gateway:
      name: eg
      namespace: envoy-gateway-system
      #The listener reference, this is used to create the HTTPRoute resource
      https_listener: https
  ingress:
    className: nginx
  #One of ingress or gateway
  type: "ingress"
  #Use these annotations to reference your certificate issuer
  #It is advised to always have a cert setup, even in a dev cluster, since everything
  #Is configured over https
  #The jhub instance will conditionally disable tls verification, if expose.enabled=false
  annotations: {
    cert-manager.io/issuer: step-issuer,
    cert-manager.io/issuer-kind: "StepClusterIssuer",
    cert-manager.io/issuer-group: "certmanager.step.sm"
    #cert-manager.io/cluster-issuer: letsencrypt-prod
  }
  #tls/ingress hostname
  hostname: "mlfw.k3s.osc.eonerc.rwth-aachen.de"

#A copy of the values of the cloudpirates minio subchart
minio-obj-storage:
  replicaCount: 1
  auth:
    rootUser: *MINIO_ROOT_USER
    rootPassword: *MINIO_ROOT_PASSWORD
  defaultBuckets: *MINIO_DEFAULT_BUCKET
  service:
    type: ClusterIP
    port: *MINIO_PORT
    consolePort: 9090

  persistence:
    enabled: true
    annotations: {}
    size: 8Gi
    accessModes:
      - ReadWriteOnce
    existingClaim: ""
    mountPath: /mnt/data

#A copy of the values of the cloudpirates postgres subchart
pgsql-db:
  replicaCount: 1
  auth:
    username: *POSTGRES_USER
    password: *POSTGRES_PASSWORD
    database: *POSTGRES_DATABASE

  service:
    type: ClusterIP
    port: *POSTGRES_PORT
    targetPort: 5432

  persistence:
    enabled: true
    annotations: {}
    size: 8Gi
    accessModes:
      - ReadWriteOnce
    existingClaim: ""
    subPath: ""
    labels: {}

#MLflow pretty much simply manages the different contexts
#In which different users are working, see the auth block comments for more
mlflow:
  minio_user: *MINIO_ROOT_USER
  minio_password: *MINIO_ROOT_PASSWORD
  minio_bucket: *MINIO_DEFAULT_BUCKET
  minio_port: *MINIO_PORT

  postgres_user: *POSTGRES_USER
  postgres_password: *POSTGRES_PASSWORD
  postgres_database: *POSTGRES_DATABASE
  postgres_port: *POSTGRES_PORT

  mlflow_admin_username: "admin"
  mlflow_admin_password: "admin420noscope"

#Federated learning configuration and remote task scheduling
#Mainly to specify who is hub and who is client
#TODO: Support remote (possibly Ray tune) or deployed cluster for task scheduling
flower:
  enabled: true
  hub_address: "flower-server-svc.flwr-tmp.svc.cluster.local:9092"
  as_hub: true
  fed_username: mlflowfed
  fed_password: mlflowfed123456
  dataset_tags:
    - "test-tag-1"
    - "test-tag-2"
  issuer_ref:
    name: step-issuer
    kind: StepClusterIssuer
    group: "certmanager.step.sm"
#A copy of the values of the Z2JH subchart
#The primary function of the hub in this app is to handle redirects from the IDP
#To create an mlflow account depending on group, create the notebook and activate 
#The mlflow UI and tensorboard extensions
jhub_central:
  hub:
    #These are the jupyterhub config templates
    extraVolumes:
      - name: jhub-extra-config
        configMap:
          name: jhub-extra-config
    extraVolumeMounts:
      #This template is used to add the previously mentioned auth hooks
      - name: jhub-extra-config
        mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/extra_config.py
        subPath: extra_config.py
        readOnly: true
      #This template is used to configure the GenericOAuthenticator dynamically from the
      #Values
      - name: jhub-extra-config
        mountPath: /usr/local/etc/jupyterhub/jupyterhub_config.d/auth_config.py
        subPath: auth_config.py
        readOnly: true
    db:
      type: sqlite-pvc
      pvc:
        accessModes:
          - ReadWriteOnce
    image:
      name: quay.io/jupyterhub/k8s-hub
      tag: "4.2.0"
  proxy:
    service:
      type: ClusterIP
    secretToken: '4d514a528099e35c7c7fd48acf9c9454ae41705412966f4a730d6c2f688cf948'
  singleuser:
    #Disallow any traffic towards anything BUT the user container itself, the hub 
    #Or the mlflow tracking server
    networkPolicy:
      enabled: false
      egress:
        - to:
          - podSelector:
              matchLabels:
                app: mlflow
          ports:
            - port: 5000
              protocol: TCP
    extraLabels:
      hub.jupyter.org/network-access-hub: "true"
    extraEnv:
      MLFLOW_TRACKING_URI:
        value: http://mlflow-svc:5000

    #When putting a notebook in the notebook folder
    #Helm then handles creating the corresponding CM
    #This is subsequently copied in an initContainer due to permission shennanigans
    initContainers:
      - name: copy-defaults
        image: alpine
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        command:
          - sh
          - -c
          - |
            echo "Copying default files to user home directory..."
            # Create home directory if it doesn't exist
            mkdir -p /home/jovyan
            if [ "$(ls -A /default-files)" ]; then
              cp -rfL /default-files/* /home/jovyan/ || echo "Warning: Some files might not have been copied"
              chown -R 1000:100 /home/jovyan/
              echo "Done copying files."
            else
              echo "No default files found to copy."
            fi
        volumeMounts:
          - name: default-files
            mountPath: /default-files
            readOnly: true
          - name: volume-{username}-{servername}
            mountPath: /home/jovyan
    allowPrivilegeEscalation: false
    uid: 1000
    fsGid: 100
    storage:
      type: dynamic
      extraVolumes:
        - name: user-extra-config
          configMap:
            name: jhub-extra-config
        - name: default-files
          configMap:
            name: default-files
        - name: home
          persistentVolumeClaim:
            claimName: claim-{username}
      extraVolumeMounts:
        #This template is used by the user container
        #To activate extensions from a payload
        #Passed by the hub in its auth_hook through the spawner.environment
        - name: user-extra-config
          mountPath: /etc/jupyter/jupyter_server_config.py
          subPath: jupyter_server_config.py
          readOnly: true
        - name: default-files
          mountPath: /default-files
          readOnly: false
      capacity: 10Gi
      homeMountPath: /home/jovyan
      dynamic:
        storageAccessModes: [ReadWriteOnce]
    #Custom user env image, pretty much just installs requirement.txt
    #Can be replaced with jupyter/tensorflow-notebook + a custom command
    image:
      name: soullessblob/tensorflow-notebook
      tag: latest
    defaultUrl: "/lab/tree/mlflow_tensorboard_examples.ipynb"
  scheduling:
    userScheduler:
      enabled: true
  cull:
    enabled: true
    timeout: 3600