apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  mlflow-admin-username: {{ .Values.mlflow.mlflow_admin_username | quote }}
  mlflow-admin-password: {{ .Values.mlflow.mlflow_admin_password | quote }}
  mlflow-fed-username: {{ .Values.flower.superlink.fed_username | quote }}
  mlflow-fed-password: {{ .Values.flower.superlink.fed_password | quote }}
  postgres-uri:  {{printf "postgresql://%s:%s@%s-pgsql-db:%d/%s" .Values.mlflow.postgres_user .Values.mlflow.postgres_password .Release.Name (int .Values.mlflow.postgres_port) .Values.mlflow.postgres_database}}
  minio-user: {{ .Values.mlflow.minio_user | quote }}
  minio-password: {{ .Values.mlflow.minio_password | quote }}
{{- if not .Values.auth.external.enabled }}
  keycloak-admin-username: {{ .Values.auth.kc_admin | default "admin" | quote }}
  keycloak-admin-password: {{ .Values.auth.kc_admin_pass | default "admin" | quote }}
{{- end }}