apiVersion: v1
kind: ConfigMap
metadata:
  name: default-files
  namespace: {{ .Release.Namespace }}
binaryData: {}
data:
  {{ range $path, $_ :=  .Files.Glob "base-app/*.{py,ipynb}" }}
    {{ base $path | nindent 2 }}: |-
{{ $.Files.Get $path | nindent 4 }}
  {{ end }}
  {{- if .Values.flower.enabled }}
  {{ range $path, $_ :=  .Files.Glob "flower-app/*.{py,ipynb}" }}
    {{ base $path | nindent 2 }}: |-
{{ $.Files.Get $path | nindent 4 }}
  {{ end }}
  pyproject.toml: |
    [project]
    name = "flower-test"
    version = "1.0.0"
    description = "Manual testing of Supernode/Superlink"
    dependencies = [
        "flwr",
        "mlflow"
    ]

    [tool.flwr.app]
    publisher = "acs"

    [tool.flwr.app.config]
    dataset_tags="test-tag-1"
    mlflow_tracking_uri=""
    mlflow_tracking_username=""
    mlflow_tracking_password=""
    mlflow_workspace=""

    [tool.flwr.app.components]
    serverapp = "server:app"
    clientapp = "client:app"

    [tool.flwr.federations]
    default = "k8s"

    [tool.flwr.federations.k8s]
    address = {{ replace "9092" "9093" (include "flower.hub_superlink" .) | quote }}
    root-certificates="/app/certs/ca.crt"
  .gitignore: |
    .config
    .flwr
    .ipynb_checkpoints
    .ipython
    .jupyter
    .keras
    .local
    mlflow_tensorboard_examples.ipynb
    .npm
    tensorboard_logger.py
    test.ipynb
  {{- end }}
