apiVersion: v1
kind: ConfigMap
metadata:
  name: default-files
  namespace: {{ .Release.Namespace }}
binaryData: {}
data:
  {{ range $path, $_ :=  .Files.Glob "files/*.{py,ipynb}" }}
    {{ base $path | nindent 2 }}: |-
{{ $.Files.Get $path | nindent 4 }}
  {{ end }}
