apiVersion: v1
kind: ConfigMap
metadata:
  name: default-files
  namespace: {{ .Release.Namespace }}
binaryData: {}
data:
  {{ range $path, $_ :=  .Files.Glob "base-app/*.{py,ipynb}" }}
    {{ base $path | nindent 2 }}: |-
{{ $.Files.Get $path | nindent 4 }}
  {{ end }}
  {{- if .Values.flower.enabled }}
  {{ range $path, $_ :=  .Files.Glob "flower-app/*.{py,toml,ipynb}" }}
    {{ base $path | nindent 2 }}: |-
{{ $.Files.Get $path | nindent 4 }}
  {{ end }}
  {{- end }}
