{{- if .Values.expose.enabled }}
{{- if eq .Values.expose.type "ingress" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jhub-ingress
  namespace: {{ .Release.Namespace }}
  {{- if .Values.expose.annotations }}
  annotations:
    {{- .Values.expose.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.expose.ingress.className }}
  tls:
    - hosts:
      - {{ .Values.expose.hostname | quote }}
      secretName: {{ printf "%s-tls" .Release.Name }}
  rules:
    - host: {{ .Values.expose.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-public
                port: { number: 80 }
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: mlflow-svc
                port: { number: 5000 }
          {{- if not .Values.auth.external.enabled }}
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: keycloak-svc
                port: { number: 8080 }
          {{- end }}
{{- if and .Values.flower.enabled .Values.flower.as_hub }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flower-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ join "," .Values.flower.ip_whitelist | quote }}
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: GRPCS
  {{- if .Values.expose.annotations }}
    {{- .Values.expose.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.expose.ingress.className }}
  tls:
    - secretName: flower-server-tls
      hosts:
        - {{ printf "flwr-sv.%s" .Values.expose.hostname | quote }}
        - {{ printf "flwr-ctrl.%s" .Values.expose.hostname | quote }}
  rules:
    - host: {{ printf "flwr-sv.%s" .Values.expose.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flower-server-svc
                port: { number: 9092 }
    - host: {{ printf "flwr-ctrl.%s" .Values.expose.hostname | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flower-server-svc
                port: { number: 9093 }
{{- end }}

{{- else if eq .Values.expose.type "gateway" }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jhub-http-route
  namespace: {{ .Release.Namespace }}
  {{- if .Values.expose.annotations }}
  annotations:
    {{- .Values.expose.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    - name: {{ .Values.expose.gateway.default_gateway.name }}
      namespace: {{ .Values.expose.gateway.default_gateway.namespace }}
      sectionName: {{ .Values.expose.gateway.default_gateway.https_listener }}
  hostnames:
    - {{ .Values.expose.hostname}}
  rules:
    - matches:
      - path:
          type: PathPrefix
          value: /
      backendRefs:
        - name: "proxy-public"
          port: 80
    - matches:
      - path:
          type: PathPrefix
          value: /mlflow
      backendRefs:
        - name: "mlflow-svc"
          port: 5000
    {{- if not .Values.auth.external.enabled }}
    - matches:
      - path:
          type: PathPrefix
          value: /auth
      backendRefs:
        - name: "keycloak-svc"
          port: 8080
    {{- end }}
    {{- if and .Values.flower.enabled .Values.flower.as_hub }}
    - matches:
      - path:
          type: PathPrefix
          value: /flower-server
      backendRefs:
        - name: "flower-server-svc"
          port: 9092
    {{- end }}
{{- else }}
  {{- fail "Unrecognized expose type, should be one of ingress or gateway" -}}
{{- end }}
{{- end }}

