{{- if and .Values.flower.enabled .Values.flower.as_hub }}
apiVersion: v1
kind: Service
metadata:
  name: flower-server-svc
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: flower-server
  ports:
    - name: fleet-api
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: control-api
      protocol: TCP
      port: 9093
      targetPort: 9093
{{- end }}