{{- if and .Values.flower.enabled (not .Values.flower.as_hub) }}
apiVersion: v1
kind: Secret
metadata:
  name: flower-client-tls
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $path, $_ :=  .Files.Glob "flower-certs/*" }}
  {{ base $path }}: {{ $.Files.Get $path | b64enc }}
  {{- end }}
{{- end }}