apiVersion: v1
kind: ConfigMap
metadata:
  name: jhub-extra-config
  namespace: {{ .Release.Namespace }}
data:
  jupyter_server_config.py: |
    import os
    import json

    c = get_config()

    # Read the config we injected from the Hub
    proxy_json = os.environ.get('PROXY_CONFIG_JSON')
    if proxy_json:
        c.ServerProxy.servers = json.loads(proxy_json)
  auth_config.py: |
    import os
    from oauthenticator.generic import GenericOAuthenticator


    #hard-coded
    c.JupyterHub.authenticator_class = 'generic-oauth'
    c.JupyterHub.admin_access = True
    c.GenericOAuthenticator.manage_groups = True
    c.GenericOAuthenticator.enable_auth_state = True
    c.GenericOAuthenticator.login_service = "keycloak"
    c.GenericOAuthenticator.username_claim = "preferred_username"
    c.GenericOAuthenticator.scope = ["openid"]
    c.GenericOAuthenticator.userdata_params = {"state":"state"}

    
    #tls verification check
    {{ $insecure := .Values.auth.insecure_skip_verify | default false -}}
    c.GenericOAuthenticator.validate_server_cert = {{ if $insecure }}False{{ else }}True{{ end }}

    #templated
    c.GenericOAuthenticator.auth_state_groups_key = {{ include "keycloak.groups_key" . | quote }}
    c.GenericOAuthenticator.client_id = {{ include "keycloak.client_id" . | quote }}
    {{ include "generate_client_secret" .}}
    c.GenericOAuthenticator.client_secret = {{ get .Release "client_secret" | quote }}
    c.GenericOAuthenticator.authorize_url = {{ include "keycloak.authorize_url" . | quote }}
    c.GenericOAuthenticator.token_url = {{ include "keycloak.token_url" . | quote }}
    c.GenericOAuthenticator.userdata_url = {{ include "keycloak.userinfo_url" . | quote }}
    c.GenericOAuthenticator.oauth_callback_url = {{- printf "%s/hub/oauth_callback" (include "app.host" .) | quote }}
    c.GenericOAuthenticator.allowed_groups = {{ include "keycloak.allowed_groups" . }}
    c.GenericOAuthenticator.admin_groups = {{ include "keycloak.admin_groups" . }}
  extra_config.py: |
    import requests
    import base64
    import secrets
    import json 

    MLFLOW_ADMIN = "{{ .Values.mlflow.mlflow_admin_username }}"
    MLFLOW_PASS = "{{ .Values.mlflow.mlflow_admin_password }}"
    GROUPS_KEY = {{ include "keycloak.groups_key" . | quote }}
    ADMIN_GROUPS = {{ include "keycloak.admin_groups" . }}
    MLFLOW_SVC = "http://mlflow-svc:5000"

    def auth_state_hook(spawner, auth_state):
        if 'MLFLOW_TRACKING_PASSWORD' in spawner.environment:
            spawner.log.info("MLflow: Hook already processed for user. Skipping API cycle.")
            return
        
        
        oauth_user = auth_state.get('oauth_user', {})
        username = oauth_user.get('preferred_username')
        password = secrets.token_hex(16)

        #increase timeout (x2)
        spawner.http_timeout = 60 
        spawner.start_timeout = 60
        
        
        spawner.volumes["00-config"] = {
            "name": "user-extra-config",
            "configMap":{
                "name": "jhub-extra-config"
            },
        }
        
        spawner.volumes["00-files"] = {
            "name": "default-files",
            "configMap":{
                "name": "default-files"
            },
        }

        spawner.volume_mounts["01-config"] = {
            "name":"user-extra-config",
            "mountPath":"/etc/jupyter/jupyter_server_config.py",
            "subPath":"jupyter_server_config.py",
            "readOnly":True
        }
        
        spawner.init_containers = [{
            "name":"copy-defaults",
            "image":"alpine",
            "securityContext":{
                "runAsUser":0,
                "runAsGroup":0
            },
            "volumeMounts":[
                {
                    "name":"default-files",
                    "mountPath":"/default-files",
                    "readOnly":True
                },
                {
                    "name":f"volume-{username}",
                    "mountPath":"/home/jovyan"
                }
            ],
            "command":["sh","-c"],
            "args":[
                """
                echo "Copying default files to user home directory..."

                # Create home directory if it doesn't exist
                mkdir -p /home/jovyan

                if [ "$(ls -A /default-files 2>/dev/null)" ]; then
                cp -rfL /default-files/* /home/jovyan/ || echo "Warning: Some files might not have been copied"
                chown -R 1000:100 /home/jovyan/
                echo "Done copying files."
                else
                echo "No default files found to copy."
                fi
                """
            ]
        }]
        spawner.allow_privilege_escalation = False
        spawner.uid = 1000
        spawner.extra_labels["hub.jupyter.org/network-access-hub"] = "true"
        spawner.fsGid = 100
        
        try:
            user_roles=auth_state
            #traverse auth_state for groups field
            for part in GROUPS_KEY.split('.'):
                user_roles = user_roles.get(part, {})

            #check admin
            is_admin = any(role in ADMIN_GROUPS for role in user_roles)

            #prep admin auth header
            auth_header = base64.b64encode(f"{MLFLOW_ADMIN}:{MLFLOW_PASS}".encode()).decode()
            headers = {"Authorization": f"Basic {auth_header}"}

            #check if user exists
            res = requests.get(f"{MLFLOW_SVC}/api/2.0/mlflow/users/get", params={"username": username}, headers=headers, timeout=5)
            
            if res.status_code == 200:
                spawner.log.info(f"MLflow: Updating session password for existing user {username}")
                #change pass
                requests.patch(
                    f"{MLFLOW_SVC}/api/2.0/mlflow/users/update-password",
                    json={"username": username, "password": password},
                    headers={**headers,"Content-Type":"application/json"},
                    timeout=5
                )
            else:
                spawner.log.info(f"MLflow: Provisioning new user {username}")
                #create user
                requests.post(
                    f"{MLFLOW_SVC}/api/2.0/mlflow/users/create",
                    json={"username": username, "password": password},
                    headers={**headers,"Content-Type":"application/json"},
                    timeout=5
                )

                #set admin
                requests.patch(
                    f"{MLFLOW_SVC}/api/2.0/mlflow/users/update-admin",
                    json={"username": username, "is_admin": is_admin},
                    headers={**headers,"Content-Type":"application/json"}, timeout=5
                )

            #conditional workspace isolation
            if not is_admin:
                workspace_name = f"ws-{username}"
            
                requests.post(f"{MLFLOW_SVC}/api/3.0/mlflow/workspaces", 
                            json={"name": workspace_name}, headers={**headers,"Content-Type":"application/json"}, timeout=5)

                res = requests.post(
                    f"{MLFLOW_SVC}/api/3.0/mlflow/roles/create", 
                    json={"name": f"{workspace_name}-user","workspace":workspace_name}, 
                    headers={**headers,"Content-Type":"application/json"},
                    timeout=5
                )
                role_id = res.json()['role']['id']

                requests.post(
                    f"{MLFLOW_SVC}/api/3.0/mlflow/roles/permissions/add", 
                    json={"permission":"MANAGE","resource_pattern":"*","resource_type":"workspace","role_id":role_id}, 
                    headers={**headers,"Content-Type":"application/json"},
                    timeout=5
                )

                requests.post(
                    f"{MLFLOW_SVC}/api/3.0/mlflow/roles/assign", 
                    json={"role_id":role_id,"username":username},
                    headers={**headers,"Content-Type":"application/json"},
                    timeout=5
                )

                spawner.environment['MLFLOW_WORKSPACE'] = workspace_name
            
            #set auth env
            spawner.environment['MLFLOW_TRACKING_USERNAME'] = username
            spawner.environment['MLFLOW_TRACKING_PASSWORD'] = password
            spawner.environment['MLFLOW_TRACKING_URI'] = MLFLOW_SVC
            spawner.environment['MLFLOW_EXTERNAL_TRACKING_URI'] = {{ include "app.host" . | quote }}

            #Use environment to create launcher entries
            auth_str = f"{username}:{password}"
            encoded_auth = base64.b64encode(auth_str.encode()).decode()
            spawner.environment['PROXY_CONFIG_JSON'] = json.dumps({
                "mlflow": {
                    "command": [
                        "socat", 
                        "TCP-LISTEN:{port},fork", 
                        "TCP:mlflow-svc:5000"
                    ],
                    "absolute_url": False,
                    "request_headers_override": {
                        "Authorization": f"Basic {encoded_auth}",
                        "Host":"mlflow-svc:5000"
                    },
                    "launcher_entry": {
                        "title": "MLflow UI",
                    }
                },
                "tensorboard": {
                    "command": [
                        "tensorboard",
                        "--logdir", "/home/jovyan/logs",
                        "--port", "{port}",
                        "--bind_all"
                    ],
                    "timeout": 20,
                    "launcher_entry": {
                        "title": "TensorBoard"
                    }
                }
            }).replace("{", "{"+"{").replace("}", "}"+"}")

            # ^The braces addition is required due to a combination of how kubespawner
            #And helm behave

        except Exception as e:
            spawner.log.error(f"MLflow Session Provisioning Failed for {username}: {e}")

    #set the auth hook
    c.Spawner.auth_state_hook = auth_state_hook
    {{- if .Values.flower.client.sidecar.enabled }}
    def flower_hook(spawner):
        if 'HAS_RAN' in spawner.environment:
            spawner.log.info("Flower: Hook already processed for user. Skipping API cycle.")
            return
        spawner.environment["HAS_RAN"] = "true"
        spawner.volumes["00-exports"] = {
            "name":"exports-vol",
            "emptyDir":{}
        }

        spawner.volumes["00-pipes"] = {
            "name":"pipes-vol",
            "emptyDir":{}
        }
        
        {{- if eq (include "flower.use_default_ca" .) "false" }}
        spawner.volumes["00-root-ca"] = {
            "name": "root-ca-vol",
            "secret":{
                "secretName":{{ include "flower.ca_secretname" . | quote }}
            }
        }
        {{- end }}

        spawner.volume_mounts["01-exports"] = {
            "name":"exports-vol",
            "mountPath":"/home/jovyan/user"
        }

        spawner.volume_mounts["01-pipes"] = {
            "name":"pipes-vol",
            "mountPath":"/home/jovyan/.pipes"
        }
        
        spawner.extra_containers = [
            {
                "name":"flower-sidecar",
                "image":"soullessblob/flower-sidecar:latest",
                "imagePullPolicy":"Always",
                "securityContext":{
                    "runAsGroup":100
                },
                "volumeMounts":[
                    {
                        "name":"exports-vol",
                        "mountPath":"/app/flower/user"
                    },
                    {
                        "name":"pipes-vol",
                        "mountPath":"/app/.pipes"
                    },
                    {{- if eq (include "flower.use_default_ca"  .) "false" }}
                    {
                        "name":"root-ca-vol",
                        "mountPath": {{ include "flower.ca_path" . | quote }},
                        "subPath":"ca.crt"
                    }
                    {{- end }}
                ],
                "env":[
                    {
                        "name":"ROOT_CERT_PATH",
                        "value": {{ include "flower.ca_path" . | quote }}
                    },
                    {
                        "name":"MLFLOW_EXTERNAL_TRACKING_URI",
                        "value":spawner.environment["MLFLOW_EXTERNAL_TRACKING_URI"]
                    },
                    {
                        "name":"PYTHONUNBUFFERED",
                        "value":"1"
                    },
                    {
                        "name":"MLFLOW_TRACKING_USERNAME",
                        "value":spawner.environment["MLFLOW_TRACKING_USERNAME"]
                    },
                    {
                        "name":"MLFLOW_TRACKING_PASSWORD",
                        "value":spawner.environment["MLFLOW_TRACKING_PASSWORD"]
                    },
                    {
                        "name":"MLFLOW_WORKSPACE",
                        "value":spawner.environment.get("MLFLOW_WORKSPACE","default")
                    },
                    {
                        "name":"SUPERLINK_CONTROL",
                        "value": {{ include "flower.superlink_control" . | quote }}
                    },
                ]
            }
        ]

    c.Spawner.pre_spawn_hook = flower_hook

    {{- end }}