apiVersion: v1
kind: ConfigMap
metadata:
  name: services-configmap
  namespace: {{ .Release.Namespace}}
data:
  minio_service_name: {{ printf "%s-minio-obj-storage" .Release.Name}}
  postgres_service_name:  {{ printf "%s-pgsql-db" .Release.Name}}
  minio_uri: {{ printf "http://%s-minio-obj-storage:%d" .Release.Name (int .Values.shared_values.minio_port)}}
  minio_port_str: {{ .Values.shared_values.minio_port | quote}}
  postgres_port_str: {{ .Values.shared_values.postgres_port | quote}}
  jhub_callback_url: {{ printf "https://%s/hub/oauth_callback" .Values.gateway.hostname}}