apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
stringData:
  MINIO_ROOT_USER: minio_user
  MINIO_ROOT_PASSWORD: minio_pwd
  MINIO_ACCESS_KEY: xrSdXTXBBiO9wuV2WnvP
  MINIO_SECRET_KEY: x7zs3RNIpaf2z8lcse6T5TprbH2WWTm1vDtBVko
  MINIO_ADDRESS: :9000
  MINIO_STORAGE_USE_HTTPS: "false"
  MINIO_CONSOLE_ADDRESS: :9001
  MINIO_PORT: "9000"
  MINIO_CONSOLE_PORT: "9001"
